services:
  - type: web
    name: student-risk-demo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python train_model.py && npm install && npm run tailwind:build
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PYTHONUNBUFFERED
        value: "true"
